---

- name: Ensure fluentd is installed
  pkgng:
    name: rubygem-fluentd
    state: present

# probably, a bug in the port
- name: install missing gems
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
    - string-scrub
    - tzinfo-data
